#!/bin/bash

echo "starting producer..."
DEBUG_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1045"
DEPLOY_DIR=../../springboot-rabbitmq-producer/target
JAVA_OPTS=-Dlog4j.configuration=log4j.properties 

JARFILE=springboot-rabbitmq-producer-0.0.1-SNAPSHOT.jar

java $JAVA_OPTS $DEBUG_OPTS -jar $DEPLOY_DIR/$JARFILE